-- MySQL Script generated by MySQL Workbench
-- Mon Jan 11 19:55:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 3wurl
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `3wurl` ;

-- -----------------------------------------------------
-- Schema 3wurl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `3wurl` DEFAULT CHARACTER SET utf8 ;
USE `3wurl` ;

-- -----------------------------------------------------
-- Table `3wurl`.`wurl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `3wurl`.`wurl` ;

CREATE TABLE IF NOT EXISTS `3wurl`.`wurl` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(100) NOT NULL,
  `target` VARCHAR(1000) NOT NULL,
  `date_created` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `3wurl`.`wurl` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `3wurl`.`visit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `3wurl`.`visit` ;

CREATE TABLE IF NOT EXISTS `3wurl`.`visit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identifier` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_views_identifier`
    FOREIGN KEY (`identifier`)
    REFERENCES `3wurl`.`wurl` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `3wurl`.`visit` (`id` ASC) VISIBLE;

CREATE INDEX `fk_views_identifier_idx` ON `3wurl`.`visit` (`identifier` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
