version: 2
jobs:
  build:
    docker:
      - image: davidde94/inertia:1.0.1
    working_directory: /Inertia
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2f:dc:22:ea:83:60:33:73:30:6d:a3:7e:98:85:d4:1c"
      - run:
          name: Setup
          command: |
              ldconfig -v
              echo 'export PATH="$PATH:/usr/local/bin/swift/usr/bin"' >> $BASH_ENV
              source $BASH_ENV
      - run:
          name: Deploy if needed
          command: |
              ls ~/.ssh
              if [ "${CIRCLE_BRANCH}" != "master" ]; then
                echo "Not master, not deploying"
                exit 0
              fi

              ssh -i ~/.ssh/id_rsa_225e5c6ff39dba762644b96a57fa5fb6 -o StrictHostKeyChecking=no -p 14815 app-inertia@main.blackpoint.co "cd Inertia && git fetch --all && git reset --hard origin/master && /usr/local/bin/swift/usr/bin/swift package update && /usr/local/bin/swift/usr/bin/swift build -c release && sudo service inertia restart"
