version: 2
jobs:
  build:
    docker:
      - image: davidde94/3wurl:1.1.0
    working_directory: ~/3wurl
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "5c:08:2f:6f:7c:65:91:8e:d7:6f:03:4b:b3:02:2f:7f"
      - run:
          name: Setup
          command: |
              ldconfig -v
              echo 'export PATH="$PATH:/usr/local/bin/swift/usr/bin"' >> $BASH_ENV
              source $BASH_ENV
      - run:
          name: Test
          command: swift test --enable-test-discovery
      - run:
          name: Deploy if needed
          command: |
              ls ~/.ssh
              if [ "${CIRCLE_BRANCH}" != "master" ]; then
                echo "Not master, not deploying"
                exit 0
              fi

              ssh -i ~/.ssh/id_rsa_5c082f6f7c65918ed76f034bb3022f7f -o StrictHostKeyChecking=no -p 14815 u_blackpoint@main.blackpoint.co "cd 3wurl && bash deploy.sh"
