name: Build and Test

on:
pull_request:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-linux:
    container: 'docker://davidde94/3wurl:2.0'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-test-discovery
